-- GENERATED by scripts/personal-schema.ts from src/main/migrations.ts. Do not edit by hand.
-- One cloud table per synced local table: same columns, plus server_updated_at (sync cursor).

-- Last-write-wins guard: an older edit never overwrites a newer one, a PC clock that is
-- ahead is clamped to server time, and rows can never change owner.
create or replace function public.sync_guard() returns trigger language plpgsql as $$
declare
  v_now text := to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
  v_cap text := to_char((now() + interval '1 minute') at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
begin
  if new.updated_at > v_cap then new.updated_at := v_now; end if;
  if tg_op = 'UPDATE' then
    if new.updated_at < old.updated_at then return old; end if;
    new.owner_id := old.owner_id;
  end if;
  new.server_updated_at := now();
  return new;
end $$;

-- profiles
create table if not exists public.profiles (id text primary key);
alter table public.profiles add column if not exists created_at text;
alter table public.profiles add column if not exists updated_at text;
alter table public.profiles add column if not exists deleted_at text;
alter table public.profiles add column if not exists owner_id text;
alter table public.profiles add column if not exists username text;
alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists mode text;
alter table public.profiles add column if not exists grade_scale text;
alter table public.profiles add column if not exists target_gpa double precision;
alter table public.profiles add column if not exists leaderboard_opt_in bigint;
alter table public.profiles add column if not exists server_updated_at timestamptz not null default now();
create index if not exists profiles_sync_idx on public.profiles (server_updated_at);
create index if not exists profiles_owner_idx on public.profiles (owner_id);
alter table public.profiles enable row level security;
drop policy if exists "own rows" on public.profiles;
create policy "own rows" on public.profiles for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.profiles from anon;
revoke delete on public.profiles from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists profiles_sync_guard on public.profiles;
create trigger profiles_sync_guard before insert or update on public.profiles for each row execute function public.sync_guard();

-- modules
create table if not exists public.modules (id text primary key);
alter table public.modules add column if not exists created_at text;
alter table public.modules add column if not exists updated_at text;
alter table public.modules add column if not exists deleted_at text;
alter table public.modules add column if not exists owner_id text;
alter table public.modules add column if not exists code text;
alter table public.modules add column if not exists name text;
alter table public.modules add column if not exists color text;
alter table public.modules add column if not exists term text;
alter table public.modules add column if not exists credits double precision;
alter table public.modules add column if not exists target_grade double precision;
alter table public.modules add column if not exists archived bigint;
alter table public.modules add column if not exists sort double precision;
alter table public.modules add column if not exists final_grade double precision;
alter table public.modules add column if not exists server_updated_at timestamptz not null default now();
create index if not exists modules_sync_idx on public.modules (server_updated_at);
create index if not exists modules_owner_idx on public.modules (owner_id);
alter table public.modules enable row level security;
drop policy if exists "own rows" on public.modules;
create policy "own rows" on public.modules for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.modules from anon;
revoke delete on public.modules from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists modules_sync_guard on public.modules;
create trigger modules_sync_guard before insert or update on public.modules for each row execute function public.sync_guard();

-- weeks
create table if not exists public.weeks (id text primary key);
alter table public.weeks add column if not exists created_at text;
alter table public.weeks add column if not exists updated_at text;
alter table public.weeks add column if not exists deleted_at text;
alter table public.weeks add column if not exists owner_id text;
alter table public.weeks add column if not exists module_id text;
alter table public.weeks add column if not exists number bigint;
alter table public.weeks add column if not exists title text;
alter table public.weeks add column if not exists start_date text;
alter table public.weeks add column if not exists server_updated_at timestamptz not null default now();
create index if not exists weeks_sync_idx on public.weeks (server_updated_at);
create index if not exists weeks_owner_idx on public.weeks (owner_id);
alter table public.weeks enable row level security;
drop policy if exists "own rows" on public.weeks;
create policy "own rows" on public.weeks for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.weeks from anon;
revoke delete on public.weeks from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists weeks_sync_guard on public.weeks;
create trigger weeks_sync_guard before insert or update on public.weeks for each row execute function public.sync_guard();

-- materials
create table if not exists public.materials (id text primary key);
alter table public.materials add column if not exists created_at text;
alter table public.materials add column if not exists updated_at text;
alter table public.materials add column if not exists deleted_at text;
alter table public.materials add column if not exists owner_id text;
alter table public.materials add column if not exists module_id text;
alter table public.materials add column if not exists week_id text;
alter table public.materials add column if not exists title text;
alter table public.materials add column if not exists kind text;
alter table public.materials add column if not exists file_name text;
alter table public.materials add column if not exists local_path text;
alter table public.materials add column if not exists size_bytes bigint;
alter table public.materials add column if not exists sha256 text;
alter table public.materials add column if not exists sync_file bigint;
alter table public.materials add column if not exists storage_path text;
alter table public.materials add column if not exists sort double precision;
alter table public.materials add column if not exists server_updated_at timestamptz not null default now();
create index if not exists materials_sync_idx on public.materials (server_updated_at);
create index if not exists materials_owner_idx on public.materials (owner_id);
alter table public.materials enable row level security;
drop policy if exists "own rows" on public.materials;
create policy "own rows" on public.materials for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.materials from anon;
revoke delete on public.materials from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists materials_sync_guard on public.materials;
create trigger materials_sync_guard before insert or update on public.materials for each row execute function public.sync_guard();

-- assessments
create table if not exists public.assessments (id text primary key);
alter table public.assessments add column if not exists created_at text;
alter table public.assessments add column if not exists updated_at text;
alter table public.assessments add column if not exists deleted_at text;
alter table public.assessments add column if not exists owner_id text;
alter table public.assessments add column if not exists module_id text;
alter table public.assessments add column if not exists title text;
alter table public.assessments add column if not exists kind text;
alter table public.assessments add column if not exists due_at text;
alter table public.assessments add column if not exists weight_pct double precision;
alter table public.assessments add column if not exists score_pct double precision;
alter table public.assessments add column if not exists is_final bigint;
alter table public.assessments add column if not exists auto_revision bigint;
alter table public.assessments add column if not exists server_updated_at timestamptz not null default now();
create index if not exists assessments_sync_idx on public.assessments (server_updated_at);
create index if not exists assessments_owner_idx on public.assessments (owner_id);
alter table public.assessments enable row level security;
drop policy if exists "own rows" on public.assessments;
create policy "own rows" on public.assessments for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.assessments from anon;
revoke delete on public.assessments from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists assessments_sync_guard on public.assessments;
create trigger assessments_sync_guard before insert or update on public.assessments for each row execute function public.sync_guard();

-- clients
create table if not exists public.clients (id text primary key);
alter table public.clients add column if not exists created_at text;
alter table public.clients add column if not exists updated_at text;
alter table public.clients add column if not exists deleted_at text;
alter table public.clients add column if not exists owner_id text;
alter table public.clients add column if not exists name text;
alter table public.clients add column if not exists color text;
alter table public.clients add column if not exists notes text;
alter table public.clients add column if not exists archived bigint;
alter table public.clients add column if not exists server_updated_at timestamptz not null default now();
create index if not exists clients_sync_idx on public.clients (server_updated_at);
create index if not exists clients_owner_idx on public.clients (owner_id);
alter table public.clients enable row level security;
drop policy if exists "own rows" on public.clients;
create policy "own rows" on public.clients for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.clients from anon;
revoke delete on public.clients from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists clients_sync_guard on public.clients;
create trigger clients_sync_guard before insert or update on public.clients for each row execute function public.sync_guard();

-- projects
create table if not exists public.projects (id text primary key);
alter table public.projects add column if not exists created_at text;
alter table public.projects add column if not exists updated_at text;
alter table public.projects add column if not exists deleted_at text;
alter table public.projects add column if not exists owner_id text;
alter table public.projects add column if not exists title text;
alter table public.projects add column if not exists description text;
alter table public.projects add column if not exists mode text;
alter table public.projects add column if not exists status text;
alter table public.projects add column if not exists deadline text;
alter table public.projects add column if not exists color text;
alter table public.projects add column if not exists module_id text;
alter table public.projects add column if not exists client_id text;
alter table public.projects add column if not exists sort double precision;
alter table public.projects add column if not exists server_updated_at timestamptz not null default now();
create index if not exists projects_sync_idx on public.projects (server_updated_at);
create index if not exists projects_owner_idx on public.projects (owner_id);
alter table public.projects enable row level security;
drop policy if exists "own rows" on public.projects;
create policy "own rows" on public.projects for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.projects from anon;
revoke delete on public.projects from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists projects_sync_guard on public.projects;
create trigger projects_sync_guard before insert or update on public.projects for each row execute function public.sync_guard();

-- milestones
create table if not exists public.milestones (id text primary key);
alter table public.milestones add column if not exists created_at text;
alter table public.milestones add column if not exists updated_at text;
alter table public.milestones add column if not exists deleted_at text;
alter table public.milestones add column if not exists owner_id text;
alter table public.milestones add column if not exists project_id text;
alter table public.milestones add column if not exists title text;
alter table public.milestones add column if not exists due_at text;
alter table public.milestones add column if not exists done_at text;
alter table public.milestones add column if not exists sort double precision;
alter table public.milestones add column if not exists server_updated_at timestamptz not null default now();
create index if not exists milestones_sync_idx on public.milestones (server_updated_at);
create index if not exists milestones_owner_idx on public.milestones (owner_id);
alter table public.milestones enable row level security;
drop policy if exists "own rows" on public.milestones;
create policy "own rows" on public.milestones for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.milestones from anon;
revoke delete on public.milestones from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists milestones_sync_guard on public.milestones;
create trigger milestones_sync_guard before insert or update on public.milestones for each row execute function public.sync_guard();

-- tasks
create table if not exists public.tasks (id text primary key);
alter table public.tasks add column if not exists created_at text;
alter table public.tasks add column if not exists updated_at text;
alter table public.tasks add column if not exists deleted_at text;
alter table public.tasks add column if not exists owner_id text;
alter table public.tasks add column if not exists title text;
alter table public.tasks add column if not exists notes text;
alter table public.tasks add column if not exists mode text;
alter table public.tasks add column if not exists status text;
alter table public.tasks add column if not exists priority bigint;
alter table public.tasks add column if not exists due_at text;
alter table public.tasks add column if not exists labels text;
alter table public.tasks add column if not exists parent_task_id text;
alter table public.tasks add column if not exists project_id text;
alter table public.tasks add column if not exists milestone_id text;
alter table public.tasks add column if not exists module_id text;
alter table public.tasks add column if not exists assessment_id text;
alter table public.tasks add column if not exists client_id text;
alter table public.tasks add column if not exists today_date text;
alter table public.tasks add column if not exists today_rank bigint;
alter table public.tasks add column if not exists sort double precision;
alter table public.tasks add column if not exists completed_at text;
alter table public.tasks add column if not exists server_updated_at timestamptz not null default now();
create index if not exists tasks_sync_idx on public.tasks (server_updated_at);
create index if not exists tasks_owner_idx on public.tasks (owner_id);
alter table public.tasks enable row level security;
drop policy if exists "own rows" on public.tasks;
create policy "own rows" on public.tasks for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.tasks from anon;
revoke delete on public.tasks from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists tasks_sync_guard on public.tasks;
create trigger tasks_sync_guard before insert or update on public.tasks for each row execute function public.sync_guard();

-- events
create table if not exists public.events (id text primary key);
alter table public.events add column if not exists created_at text;
alter table public.events add column if not exists updated_at text;
alter table public.events add column if not exists deleted_at text;
alter table public.events add column if not exists owner_id text;
alter table public.events add column if not exists title text;
alter table public.events add column if not exists start_at text;
alter table public.events add column if not exists end_at text;
alter table public.events add column if not exists all_day bigint;
alter table public.events add column if not exists color text;
alter table public.events add column if not exists notes text;
alter table public.events add column if not exists task_id text;
alter table public.events add column if not exists module_id text;
alter table public.events add column if not exists assessment_id text;
alter table public.events add column if not exists server_updated_at timestamptz not null default now();
create index if not exists events_sync_idx on public.events (server_updated_at);
create index if not exists events_owner_idx on public.events (owner_id);
alter table public.events enable row level security;
drop policy if exists "own rows" on public.events;
create policy "own rows" on public.events for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.events from anon;
revoke delete on public.events from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists events_sync_guard on public.events;
create trigger events_sync_guard before insert or update on public.events for each row execute function public.sync_guard();

-- calendar_subscriptions
create table if not exists public.calendar_subscriptions (id text primary key);
alter table public.calendar_subscriptions add column if not exists created_at text;
alter table public.calendar_subscriptions add column if not exists updated_at text;
alter table public.calendar_subscriptions add column if not exists deleted_at text;
alter table public.calendar_subscriptions add column if not exists owner_id text;
alter table public.calendar_subscriptions add column if not exists name text;
alter table public.calendar_subscriptions add column if not exists url text;
alter table public.calendar_subscriptions add column if not exists color text;
alter table public.calendar_subscriptions add column if not exists enabled bigint;
alter table public.calendar_subscriptions add column if not exists last_fetched_at text;
alter table public.calendar_subscriptions add column if not exists last_error text;
alter table public.calendar_subscriptions add column if not exists server_updated_at timestamptz not null default now();
create index if not exists calendar_subscriptions_sync_idx on public.calendar_subscriptions (server_updated_at);
create index if not exists calendar_subscriptions_owner_idx on public.calendar_subscriptions (owner_id);
alter table public.calendar_subscriptions enable row level security;
drop policy if exists "own rows" on public.calendar_subscriptions;
create policy "own rows" on public.calendar_subscriptions for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.calendar_subscriptions from anon;
revoke delete on public.calendar_subscriptions from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists calendar_subscriptions_sync_guard on public.calendar_subscriptions;
create trigger calendar_subscriptions_sync_guard before insert or update on public.calendar_subscriptions for each row execute function public.sync_guard();

-- focus_sessions
create table if not exists public.focus_sessions (id text primary key);
alter table public.focus_sessions add column if not exists created_at text;
alter table public.focus_sessions add column if not exists updated_at text;
alter table public.focus_sessions add column if not exists deleted_at text;
alter table public.focus_sessions add column if not exists owner_id text;
alter table public.focus_sessions add column if not exists kind text;
alter table public.focus_sessions add column if not exists started_at text;
alter table public.focus_sessions add column if not exists ended_at text;
alter table public.focus_sessions add column if not exists planned_minutes bigint;
alter table public.focus_sessions add column if not exists focused_seconds bigint;
alter table public.focus_sessions add column if not exists completed bigint;
alter table public.focus_sessions add column if not exists mode text;
alter table public.focus_sessions add column if not exists task_id text;
alter table public.focus_sessions add column if not exists module_id text;
alter table public.focus_sessions add column if not exists project_id text;
alter table public.focus_sessions add column if not exists shared_timer_id text;
alter table public.focus_sessions add column if not exists language_id text;
alter table public.focus_sessions add column if not exists server_updated_at timestamptz not null default now();
create index if not exists focus_sessions_sync_idx on public.focus_sessions (server_updated_at);
create index if not exists focus_sessions_owner_idx on public.focus_sessions (owner_id);
alter table public.focus_sessions enable row level security;
drop policy if exists "own rows" on public.focus_sessions;
create policy "own rows" on public.focus_sessions for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.focus_sessions from anon;
revoke delete on public.focus_sessions from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists focus_sessions_sync_guard on public.focus_sessions;
create trigger focus_sessions_sync_guard before insert or update on public.focus_sessions for each row execute function public.sync_guard();

-- timetable_slots
create table if not exists public.timetable_slots (id text primary key);
alter table public.timetable_slots add column if not exists created_at text;
alter table public.timetable_slots add column if not exists updated_at text;
alter table public.timetable_slots add column if not exists deleted_at text;
alter table public.timetable_slots add column if not exists owner_id text;
alter table public.timetable_slots add column if not exists module_id text;
alter table public.timetable_slots add column if not exists kind text;
alter table public.timetable_slots add column if not exists weekday bigint;
alter table public.timetable_slots add column if not exists start_time text;
alter table public.timetable_slots add column if not exists end_time text;
alter table public.timetable_slots add column if not exists location text;
alter table public.timetable_slots add column if not exists valid_from text;
alter table public.timetable_slots add column if not exists valid_to text;
alter table public.timetable_slots add column if not exists server_updated_at timestamptz not null default now();
create index if not exists timetable_slots_sync_idx on public.timetable_slots (server_updated_at);
create index if not exists timetable_slots_owner_idx on public.timetable_slots (owner_id);
alter table public.timetable_slots enable row level security;
drop policy if exists "own rows" on public.timetable_slots;
create policy "own rows" on public.timetable_slots for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.timetable_slots from anon;
revoke delete on public.timetable_slots from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists timetable_slots_sync_guard on public.timetable_slots;
create trigger timetable_slots_sync_guard before insert or update on public.timetable_slots for each row execute function public.sync_guard();

-- notes
create table if not exists public.notes (id text primary key);
alter table public.notes add column if not exists created_at text;
alter table public.notes add column if not exists updated_at text;
alter table public.notes add column if not exists deleted_at text;
alter table public.notes add column if not exists owner_id text;
alter table public.notes add column if not exists title text;
alter table public.notes add column if not exists content text;
alter table public.notes add column if not exists plain_text text;
alter table public.notes add column if not exists kind text;
alter table public.notes add column if not exists mode text;
alter table public.notes add column if not exists module_id text;
alter table public.notes add column if not exists week_id text;
alter table public.notes add column if not exists project_id text;
alter table public.notes add column if not exists client_id text;
alter table public.notes add column if not exists meeting_at text;
alter table public.notes add column if not exists pinned bigint;
alter table public.notes add column if not exists server_updated_at timestamptz not null default now();
create index if not exists notes_sync_idx on public.notes (server_updated_at);
create index if not exists notes_owner_idx on public.notes (owner_id);
alter table public.notes enable row level security;
drop policy if exists "own rows" on public.notes;
create policy "own rows" on public.notes for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.notes from anon;
revoke delete on public.notes from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists notes_sync_guard on public.notes;
create trigger notes_sync_guard before insert or update on public.notes for each row execute function public.sync_guard();

-- mindmaps
create table if not exists public.mindmaps (id text primary key);
alter table public.mindmaps add column if not exists created_at text;
alter table public.mindmaps add column if not exists updated_at text;
alter table public.mindmaps add column if not exists deleted_at text;
alter table public.mindmaps add column if not exists owner_id text;
alter table public.mindmaps add column if not exists title text;
alter table public.mindmaps add column if not exists mode text;
alter table public.mindmaps add column if not exists module_id text;
alter table public.mindmaps add column if not exists server_updated_at timestamptz not null default now();
create index if not exists mindmaps_sync_idx on public.mindmaps (server_updated_at);
create index if not exists mindmaps_owner_idx on public.mindmaps (owner_id);
alter table public.mindmaps enable row level security;
drop policy if exists "own rows" on public.mindmaps;
create policy "own rows" on public.mindmaps for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.mindmaps from anon;
revoke delete on public.mindmaps from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists mindmaps_sync_guard on public.mindmaps;
create trigger mindmaps_sync_guard before insert or update on public.mindmaps for each row execute function public.sync_guard();

-- mindmap_nodes
create table if not exists public.mindmap_nodes (id text primary key);
alter table public.mindmap_nodes add column if not exists created_at text;
alter table public.mindmap_nodes add column if not exists updated_at text;
alter table public.mindmap_nodes add column if not exists deleted_at text;
alter table public.mindmap_nodes add column if not exists owner_id text;
alter table public.mindmap_nodes add column if not exists mindmap_id text;
alter table public.mindmap_nodes add column if not exists label text;
alter table public.mindmap_nodes add column if not exists x double precision;
alter table public.mindmap_nodes add column if not exists y double precision;
alter table public.mindmap_nodes add column if not exists color text;
alter table public.mindmap_nodes add column if not exists link_type text;
alter table public.mindmap_nodes add column if not exists link_id text;
alter table public.mindmap_nodes add column if not exists server_updated_at timestamptz not null default now();
create index if not exists mindmap_nodes_sync_idx on public.mindmap_nodes (server_updated_at);
create index if not exists mindmap_nodes_owner_idx on public.mindmap_nodes (owner_id);
alter table public.mindmap_nodes enable row level security;
drop policy if exists "own rows" on public.mindmap_nodes;
create policy "own rows" on public.mindmap_nodes for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.mindmap_nodes from anon;
revoke delete on public.mindmap_nodes from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists mindmap_nodes_sync_guard on public.mindmap_nodes;
create trigger mindmap_nodes_sync_guard before insert or update on public.mindmap_nodes for each row execute function public.sync_guard();

-- mindmap_edges
create table if not exists public.mindmap_edges (id text primary key);
alter table public.mindmap_edges add column if not exists created_at text;
alter table public.mindmap_edges add column if not exists updated_at text;
alter table public.mindmap_edges add column if not exists deleted_at text;
alter table public.mindmap_edges add column if not exists owner_id text;
alter table public.mindmap_edges add column if not exists mindmap_id text;
alter table public.mindmap_edges add column if not exists source_node_id text;
alter table public.mindmap_edges add column if not exists target_node_id text;
alter table public.mindmap_edges add column if not exists label text;
alter table public.mindmap_edges add column if not exists server_updated_at timestamptz not null default now();
create index if not exists mindmap_edges_sync_idx on public.mindmap_edges (server_updated_at);
create index if not exists mindmap_edges_owner_idx on public.mindmap_edges (owner_id);
alter table public.mindmap_edges enable row level security;
drop policy if exists "own rows" on public.mindmap_edges;
create policy "own rows" on public.mindmap_edges for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.mindmap_edges from anon;
revoke delete on public.mindmap_edges from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists mindmap_edges_sync_guard on public.mindmap_edges;
create trigger mindmap_edges_sync_guard before insert or update on public.mindmap_edges for each row execute function public.sync_guard();

-- flashcard_decks
create table if not exists public.flashcard_decks (id text primary key);
alter table public.flashcard_decks add column if not exists created_at text;
alter table public.flashcard_decks add column if not exists updated_at text;
alter table public.flashcard_decks add column if not exists deleted_at text;
alter table public.flashcard_decks add column if not exists owner_id text;
alter table public.flashcard_decks add column if not exists name text;
alter table public.flashcard_decks add column if not exists module_id text;
alter table public.flashcard_decks add column if not exists server_updated_at timestamptz not null default now();
create index if not exists flashcard_decks_sync_idx on public.flashcard_decks (server_updated_at);
create index if not exists flashcard_decks_owner_idx on public.flashcard_decks (owner_id);
alter table public.flashcard_decks enable row level security;
drop policy if exists "own rows" on public.flashcard_decks;
create policy "own rows" on public.flashcard_decks for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.flashcard_decks from anon;
revoke delete on public.flashcard_decks from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists flashcard_decks_sync_guard on public.flashcard_decks;
create trigger flashcard_decks_sync_guard before insert or update on public.flashcard_decks for each row execute function public.sync_guard();

-- flashcards
create table if not exists public.flashcards (id text primary key);
alter table public.flashcards add column if not exists created_at text;
alter table public.flashcards add column if not exists updated_at text;
alter table public.flashcards add column if not exists deleted_at text;
alter table public.flashcards add column if not exists owner_id text;
alter table public.flashcards add column if not exists deck_id text;
alter table public.flashcards add column if not exists front text;
alter table public.flashcards add column if not exists back text;
alter table public.flashcards add column if not exists ease double precision;
alter table public.flashcards add column if not exists interval_days bigint;
alter table public.flashcards add column if not exists repetitions bigint;
alter table public.flashcards add column if not exists due_at text;
alter table public.flashcards add column if not exists last_reviewed_at text;
alter table public.flashcards add column if not exists server_updated_at timestamptz not null default now();
create index if not exists flashcards_sync_idx on public.flashcards (server_updated_at);
create index if not exists flashcards_owner_idx on public.flashcards (owner_id);
alter table public.flashcards enable row level security;
drop policy if exists "own rows" on public.flashcards;
create policy "own rows" on public.flashcards for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.flashcards from anon;
revoke delete on public.flashcards from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists flashcards_sync_guard on public.flashcards;
create trigger flashcards_sync_guard before insert or update on public.flashcards for each row execute function public.sync_guard();

-- videos
create table if not exists public.videos (id text primary key);
alter table public.videos add column if not exists created_at text;
alter table public.videos add column if not exists updated_at text;
alter table public.videos add column if not exists deleted_at text;
alter table public.videos add column if not exists owner_id text;
alter table public.videos add column if not exists url text;
alter table public.videos add column if not exists youtube_id text;
alter table public.videos add column if not exists title text;
alter table public.videos add column if not exists author text;
alter table public.videos add column if not exists thumbnail_url text;
alter table public.videos add column if not exists start_seconds bigint;
alter table public.videos add column if not exists tags text;
alter table public.videos add column if not exists notes text;
alter table public.videos add column if not exists mode text;
alter table public.videos add column if not exists module_id text;
alter table public.videos add column if not exists server_updated_at timestamptz not null default now();
create index if not exists videos_sync_idx on public.videos (server_updated_at);
create index if not exists videos_owner_idx on public.videos (owner_id);
alter table public.videos enable row level security;
drop policy if exists "own rows" on public.videos;
create policy "own rows" on public.videos for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.videos from anon;
revoke delete on public.videos from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists videos_sync_guard on public.videos;
create trigger videos_sync_guard before insert or update on public.videos for each row execute function public.sync_guard();

-- inbox_items
create table if not exists public.inbox_items (id text primary key);
alter table public.inbox_items add column if not exists created_at text;
alter table public.inbox_items add column if not exists updated_at text;
alter table public.inbox_items add column if not exists deleted_at text;
alter table public.inbox_items add column if not exists owner_id text;
alter table public.inbox_items add column if not exists text text;
alter table public.inbox_items add column if not exists processed_at text;
alter table public.inbox_items add column if not exists converted_to_type text;
alter table public.inbox_items add column if not exists converted_to_id text;
alter table public.inbox_items add column if not exists server_updated_at timestamptz not null default now();
create index if not exists inbox_items_sync_idx on public.inbox_items (server_updated_at);
create index if not exists inbox_items_owner_idx on public.inbox_items (owner_id);
alter table public.inbox_items enable row level security;
drop policy if exists "own rows" on public.inbox_items;
create policy "own rows" on public.inbox_items for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.inbox_items from anon;
revoke delete on public.inbox_items from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists inbox_items_sync_guard on public.inbox_items;
create trigger inbox_items_sync_guard before insert or update on public.inbox_items for each row execute function public.sync_guard();

-- game_state
create table if not exists public.game_state (id text primary key);
alter table public.game_state add column if not exists created_at text;
alter table public.game_state add column if not exists updated_at text;
alter table public.game_state add column if not exists deleted_at text;
alter table public.game_state add column if not exists owner_id text;
alter table public.game_state add column if not exists currency double precision;
alter table public.game_state add column if not exists state text;
alter table public.game_state add column if not exists server_updated_at timestamptz not null default now();
create index if not exists game_state_sync_idx on public.game_state (server_updated_at);
create index if not exists game_state_owner_idx on public.game_state (owner_id);
alter table public.game_state enable row level security;
drop policy if exists "own rows" on public.game_state;
create policy "own rows" on public.game_state for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.game_state from anon;
revoke delete on public.game_state from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists game_state_sync_guard on public.game_state;
create trigger game_state_sync_guard before insert or update on public.game_state for each row execute function public.sync_guard();

-- languages
create table if not exists public.languages (id text primary key);
alter table public.languages add column if not exists created_at text;
alter table public.languages add column if not exists updated_at text;
alter table public.languages add column if not exists deleted_at text;
alter table public.languages add column if not exists owner_id text;
alter table public.languages add column if not exists name text;
alter table public.languages add column if not exists native_name text;
alter table public.languages add column if not exists code text;
alter table public.languages add column if not exists flag text;
alter table public.languages add column if not exists color text;
alter table public.languages add column if not exists level text;
alter table public.languages add column if not exists target_level text;
alter table public.languages add column if not exists target_date text;
alter table public.languages add column if not exists daily_goal_min bigint;
alter table public.languages add column if not exists deck_id text;
alter table public.languages add column if not exists resources text;
alter table public.languages add column if not exists why text;
alter table public.languages add column if not exists active bigint;
alter table public.languages add column if not exists sort double precision;
alter table public.languages add column if not exists server_updated_at timestamptz not null default now();
create index if not exists languages_sync_idx on public.languages (server_updated_at);
create index if not exists languages_owner_idx on public.languages (owner_id);
alter table public.languages enable row level security;
drop policy if exists "own rows" on public.languages;
create policy "own rows" on public.languages for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.languages from anon;
revoke delete on public.languages from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists languages_sync_guard on public.languages;
create trigger languages_sync_guard before insert or update on public.languages for each row execute function public.sync_guard();

-- language_logs
create table if not exists public.language_logs (id text primary key);
alter table public.language_logs add column if not exists created_at text;
alter table public.language_logs add column if not exists updated_at text;
alter table public.language_logs add column if not exists deleted_at text;
alter table public.language_logs add column if not exists owner_id text;
alter table public.language_logs add column if not exists language_id text;
alter table public.language_logs add column if not exists date text;
alter table public.language_logs add column if not exists minutes bigint;
alter table public.language_logs add column if not exists skill text;
alter table public.language_logs add column if not exists activity text;
alter table public.language_logs add column if not exists server_updated_at timestamptz not null default now();
create index if not exists language_logs_sync_idx on public.language_logs (server_updated_at);
create index if not exists language_logs_owner_idx on public.language_logs (owner_id);
alter table public.language_logs enable row level security;
drop policy if exists "own rows" on public.language_logs;
create policy "own rows" on public.language_logs for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.language_logs from anon;
revoke delete on public.language_logs from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists language_logs_sync_guard on public.language_logs;
create trigger language_logs_sync_guard before insert or update on public.language_logs for each row execute function public.sync_guard();

-- habits
create table if not exists public.habits (id text primary key);
alter table public.habits add column if not exists created_at text;
alter table public.habits add column if not exists updated_at text;
alter table public.habits add column if not exists deleted_at text;
alter table public.habits add column if not exists owner_id text;
alter table public.habits add column if not exists name text;
alter table public.habits add column if not exists emoji text;
alter table public.habits add column if not exists color text;
alter table public.habits add column if not exists days_per_week bigint;
alter table public.habits add column if not exists archived bigint;
alter table public.habits add column if not exists sort double precision;
alter table public.habits add column if not exists server_updated_at timestamptz not null default now();
create index if not exists habits_sync_idx on public.habits (server_updated_at);
create index if not exists habits_owner_idx on public.habits (owner_id);
alter table public.habits enable row level security;
drop policy if exists "own rows" on public.habits;
create policy "own rows" on public.habits for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.habits from anon;
revoke delete on public.habits from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists habits_sync_guard on public.habits;
create trigger habits_sync_guard before insert or update on public.habits for each row execute function public.sync_guard();

-- habit_checks
create table if not exists public.habit_checks (id text primary key);
alter table public.habit_checks add column if not exists created_at text;
alter table public.habit_checks add column if not exists updated_at text;
alter table public.habit_checks add column if not exists deleted_at text;
alter table public.habit_checks add column if not exists owner_id text;
alter table public.habit_checks add column if not exists habit_id text;
alter table public.habit_checks add column if not exists date text;
alter table public.habit_checks add column if not exists server_updated_at timestamptz not null default now();
create index if not exists habit_checks_sync_idx on public.habit_checks (server_updated_at);
create index if not exists habit_checks_owner_idx on public.habit_checks (owner_id);
alter table public.habit_checks enable row level security;
drop policy if exists "own rows" on public.habit_checks;
create policy "own rows" on public.habit_checks for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);
revoke all on public.habit_checks from anon;
revoke delete on public.habit_checks from authenticated; -- deletes are soft (deleted_at)
drop trigger if exists habit_checks_sync_guard on public.habit_checks;
create trigger habit_checks_sync_guard before insert or update on public.habit_checks for each row execute function public.sync_guard();
