// Generates the cloud (Postgres) version of every synced personal table straight from
// the app's own SQLite migrations, so local and cloud columns can never drift apart.
// Bundled and run by scripts/cloud-setup.cjs.

import { DatabaseSync } from 'node:sqlite'
import { migrations } from '../src/main/migrations'
import { SYNC_TABLES } from '../src/shared/sync'

const PG_TYPE: Record<string, string> = { INTEGER: 'bigint', REAL: 'double precision', TEXT: 'text' }

export function personalSql(): string {
  const db = new DatabaseSync(':memory:')
  for (const m of migrations) typeof m === 'function' ? m(db) : db.exec(m)

  const out: string[] = [
    '-- GENERATED by scripts/personal-schema.ts from src/main/migrations.ts. Do not edit by hand.',
    '-- One cloud table per synced local table: same columns, plus server_updated_at (sync cursor).',
    '',
    '-- Last-write-wins guard: an older edit never overwrites a newer one, a PC clock that is',
    '-- ahead is clamped to server time, and rows can never change owner.',
    `create or replace function public.sync_guard() returns trigger language plpgsql as $$
declare
  v_now text := to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
  v_cap text := to_char((now() + interval '1 minute') at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
begin
  if new.updated_at > v_cap then new.updated_at := v_now; end if;
  if tg_op = 'UPDATE' then
    if new.updated_at < old.updated_at then return old; end if;
    new.owner_id := old.owner_id;
  end if;
  new.server_updated_at := now();
  return new;
end $$;`,
    ''
  ]

  for (const table of SYNC_TABLES) {
    const cols = db.prepare(`PRAGMA table_info(${table})`).all() as { name: string; type: string }[]
    out.push(`-- ${table}`)
    out.push(`create table if not exists public.${table} (id text primary key);`)
    for (const c of cols) {
      if (c.name === 'id') continue
      out.push(`alter table public.${table} add column if not exists ${c.name} ${PG_TYPE[c.type.toUpperCase()] ?? 'text'};`)
    }
    out.push(
      `alter table public.${table} add column if not exists server_updated_at timestamptz not null default now();`,
      `create index if not exists ${table}_sync_idx on public.${table} (server_updated_at);`,
      `create index if not exists ${table}_owner_idx on public.${table} (owner_id);`,
      `alter table public.${table} enable row level security;`,
      `drop policy if exists "own rows" on public.${table};`,
      `create policy "own rows" on public.${table} for all to authenticated using (owner_id = auth.uid()::text) with check (owner_id = auth.uid()::text);`,
      `revoke all on public.${table} from anon;`,
      `revoke delete on public.${table} from authenticated; -- deletes are soft (deleted_at)`,
      `drop trigger if exists ${table}_sync_guard on public.${table};`,
      `create trigger ${table}_sync_guard before insert or update on public.${table} for each row execute function public.sync_guard();`,
      ''
    )
  }
  return out.join('\n')
}
